; PlatformIO Project Configuration File
;
; Two environments: one per ESP.
;   pio run -e slave -t upload --upload-port COMx
;   pio run -e master -t upload --upload-port COMx
;   pio device monitor -e slave --port COMx
;   pio device monitor -e master --port COMx

[env:slave]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<shared/BQ76952.cpp> +<slaves/sender.cpp>
build_flags = -Isrc/shared

[env:master]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<master/reciever.cpp>
build_flags = -Isrc/shared
lib_deps = knolleary/PubSubClient@^2.8
	https://github.com/tzapu/WiFiManager.git

[env:tb_dashboard]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<shared/BQ76952.cpp> +<testboard/dashboard.cpp>
build_flags = -Isrc/shared -Isrc/testboard

[env:tb_bq_node]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<testboard/bq_node.cpp>
build_flags = -Isrc/shared -Isrc/testboard