; PlatformIO Project Configuration File
;
; Two environments: one per ESP.
;   pio run -e slave -t upload --upload-port COMx
;   pio run -e master -t upload --upload-port COMx
;   pio device monitor -e slave --port COMx
;   pio device monitor -e master --port COMx

[env:slave]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<shared/BQ76952.cpp> +<slaves/sender.cpp>
build_flags = -Isrc/shared

[env:slave_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_src_filter = -<*> +<shared/BQ76952.cpp> +<slaves/sender.cpp>
build_flags = -Isrc/shared -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1

[env:master]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<master/reciever.cpp>
build_flags = -Isrc/shared
lib_deps = knolleary/PubSubClient@^2.8
	https://github.com/tzapu/WiFiManager.git

[env:tb_dashboard]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<shared/BQ76952.cpp> +<testboard/New_Dashboard.cpp>
build_flags = -Isrc/shared -Isrc/testboard

[env:tb_dashboard_v2]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<shared/BQ76952.cpp> +<testboard_v2/New_Dashboard.cpp>
build_flags = -Isrc/shared -Isrc/testboard_v2

[env:tb_bq_node]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<testboard/bq_node.cpp>
build_flags = -Isrc/shared -Isrc/testboard

[env:soh_test]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<soh_test/main.cpp>
build_flags = -Isrc/testboard_v2

[env:testboard_user_edition]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<shared/BQ76952.cpp> +<testboard_user_edition/New_Dashboard.cpp>
build_flags = -Isrc/shared -Isrc/testboard_user_edition

[env:mainboard_dashboard]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_src_filter = -<*> +<shared/BQ76952.cpp> +<mainboard_dashboard/New_Dashboard.cpp>
build_flags = -Isrc/shared -Isrc/mainboard_dashboard -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1

[env:mainboard_comm_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_src_filter = -<*> +<mainboard_comm_test/main.cpp>
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1